import os
import json
import re
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

client = OpenAI(
    base_url="https://integrate.api.nvidia.com/v1",
    api_key=os.getenv("NVIDIA_API_KEY")
)

MODEL = os.getenv("NVIDIA_MODEL", "deepseek-ai/deepseek-v4-pro-0813")

STRUCTURE_PROMPT = """You are refining an already-generated form schema. You are NOT performing OCR — that step is done. Your job is to fix ONE specific problem: detecting rating tables/matrices that were incorrectly split into many separate fields.

You will receive:
1. The original extracted text (for context on layout).
2. A "rawSchema" - a FLAT JSON ARRAY already generated by another model, which may contain mistakes like:
   - Turning each column option (e.g. "Excellent", "Very Good", "Good", "Fair", "Poor") into a separate field.
   - Turning each row of a rating table into repeated fields with the same options.
   - Missing a proper "declaration" marking for declaration/confirmation text.

YOUR TASK: return a corrected FLAT JSON ARRAY (same flat structure, NOT nested) where:

1. Any rating table (a set of consecutive rows that all share the SAME column options, like Excellent/Very Good/Good/Fair/Poor) becomes ONE object:
   {"type":"rating_matrix","label":"<a short label describing what's being rated>","required":true,"columns":["Excellent","Very Good","Good","Fair","Poor"],"rows":["Quality of teaching","Clarity of explanation by faculty", ...]}

2. Declaration/confirmation paragraph text becomes:
   {"type":"declaration","label":"<the declaration text>"}

3. Headings stay as: {"type":"heading","label":"..."}

4. Normal fields (text, date, tel, email, textarea, number, radio with real distinct options, checkbox, dropdown) stay exactly as they were, unchanged, in their original position/order.

5. Preserve overall document order: headings, then normal fields, then rating_matrix, then more fields, then declaration, etc. - matching the original document's flow.

STRICT RULES:
- Do NOT invent rows or columns that weren't in the original text/rawSchema.
- Do NOT merge two DIFFERENT rating tables (different row sets) into one matrix.
- Only convert repeated identical-options fields into a rating_matrix if there are at least 3 rows sharing the exact same set of options - a single isolated radio question with options is NOT a matrix, leave it as a normal "radio" field.
- Return ONLY the corrected flat JSON array. No explanation, no markdown fences.
"""

def clean_json_array(raw: str):
    cleaned = re.sub(r"```json|```", "", raw, flags=re.IGNORECASE).strip()
    start = cleaned.find("[")
    end = cleaned.rfind("]")
    if start != -1 and end != -1:
        cleaned = cleaned[start:end+1]
    return cleaned

def structure_schema(extracted_text: str, raw_schema: list) -> dict:
    user_content = (
        STRUCTURE_PROMPT
        + "\n\nORIGINAL EXTRACTED TEXT:\n" + extracted_text
        + "\n\nRAW SCHEMA TO FIX:\n" + json.dumps(raw_schema)
    )

    try:
        completion = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": user_content}],
            temperature=0.2,
            max_tokens=4096,
            stream=False
        )
        raw = completion.choices[0].message.content
        cleaned = clean_json_array(raw)
        parsed = json.loads(cleaned)

        if not isinstance(parsed, list):
            return {"error": "NVIDIA model did not return a JSON array", "raw": cleaned, "formSchema": raw_schema}

        return {"formSchema": parsed}

    except json.JSONDecodeError as e:
        return {"error": f"Invalid JSON from NVIDIA model: {e}", "formSchema": raw_schema}
    except Exception as e:
        return {"error": f"NVIDIA API call failed: {e}", "formSchema": raw_schema}
